stages:
  - test

jobs:
  include:
    - stage: test
      language: python
      python: '2.7'
      install:
        - easy_install distribute
        - pip install -r requirements.txt
      script: pytest
    - stage: test
      language: node_js
      node_js:
        - 10
        - 9
        - 8
        - 7
        - 6
      script:
        - npm run grunt -- --version
        - npm run grunt -- build
    - stage: test
      language: bash
      sudo: required
      services:
        - docker
      script: docker build . -t webmole/crawler-benchmark
