language: python
python:
- '2.7'
# - '3.3'

install:
  - easy_install distribute
  - pip install -r requirements.txt

test:
  - pytest

stages:
  - docker

jobs:
  include:
    - stage: docker
      language: bash
      sudo: required
      services:
        - docker
      script: docker build . -t webmole/crawler-benchmark

