stages:
  - python
  - docker

jobs:
  include:
    - stage: python
      language: python
      python: '2.7'
      install:
        - easy_install distribute
        - pip install -r requirements.txt
      script: pytest
    - stage: docker
      language: bash
      sudo: required
      services:
        - docker
      script: docker build . -t webmole/crawler-benchmark

