stages:
  - test

jobs:
  include:
    - stage: test
      language: python
      python: '2.7'
      install:
        - easy_install distribute
        - pip install -r requirements.txt
      script: pytest
    - stage: test
      language: node
      node:
        - 1.10
      install:
        - npm i
      test:
        - npm run grunt -- build
    - stage: test
      language: bash
      sudo: required
      services:
        - docker
      script: docker build . -t webmole/crawler-benchmark

