stages:
  - test

jobs:
  include:
    - stage: test
      language: python
      python: '2.7'
      install:
        - easy_install distribute
        - pip install -r requirements.txt
      script: pytest --cov --cov-report term:skip-covered
      after_success:
        - codecov
    - stage: test
      language: node_js
      node_js: 10
      script:
        - npm run grunt -- --version
        - npm run grunt -- build
    - stage: test
      language: bash
      sudo: required
      services:
        - docker
      script: |
        export IMAGE_NAME=webmole/crawler-benchmark
        docker build . -t $IMAGE_NAME:$COMMIT
        if [ "$TRAVIS_BRANCH" == "master" ]; then
          docker login -u $REGISTRY_USER -p $REGISTRY_PASS
          docker push "${IMAGE_NAME}:${COMMIT}"
          docker tag $IMAGE_NAME:$COMMIT $IMAGE_NAME:latest
          docker push "${IMAGE_NAME}:latest"
        fi
