version: '3'
services:
  website:
    build: .
    ports:
      - 8080:8080
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - postgres
    tty: true
    command: ./wait-for-postgres.sh python runserver.py
  postgres:
    image: postgres:10.4
    restart: always
    env_file:
      - .env
    ports:
      - 5432:5432