version: '3'
services:
  website:
    build: .
    ports:
      - 8080:8080
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - postgres
    tty: true
    entrypoint: ./wait-for-postgres.sh
    command: python runserver.py
  postgres:
    image: postgres:10.4
    env_file:
      - .env
    ports:
      - 5432:5432